# Generated by Django 2.1 on 2018-10-03 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180929_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 15, 8, 26, 677109, tzinfo=utc)),
        ),
    ]
